#!/usr/bin/env bash
# kanban-schema.sh — Centralized KANBAN.md schema definitions
# Source this file; do not execute directly.

# Section names (order matters for workflow: Backlog → In Progress → Review → Done)
KANBAN_SECTIONS=("Backlog" "In Progress" "Review" "Done")

# Column headers per section
KANBAN_HEADER_BACKLOG="| ID | Title | Assigned | Created | Priority | Description |"
KANBAN_HEADER_IN_PROGRESS="| ID | Title | Assigned | Status | Started | Description |"
KANBAN_HEADER_REVIEW="| ID | Title | Assigned | Status | Submitted | Artifacts |"
KANBAN_HEADER_DONE="| ID | Title | Completed | Summary | Artifacts |"

# Column counts per section
KANBAN_COLS_BACKLOG=6
KANBAN_COLS_IN_PROGRESS=6
KANBAN_COLS_REVIEW=6
KANBAN_COLS_DONE=5

# Generate table separator for a given column count
kanban_separator() {
  local cols="$1" sep="|"
  for ((i=0; i<cols; i++)); do sep="${sep}---|"; done
  echo "$sep"
}

# Get header string for a section
kanban_header_for_section() {
  local section="$1"
  case "$section" in
    "Backlog")      echo "$KANBAN_HEADER_BACKLOG" ;;
    "In Progress")  echo "$KANBAN_HEADER_IN_PROGRESS" ;;
    "Review")       echo "$KANBAN_HEADER_REVIEW" ;;
    "Done")         echo "$KANBAN_HEADER_DONE" ;;
    *)              return 1 ;;
  esac
}

# Get column count for a section
kanban_cols_for_section() {
  local section="$1"
  case "$section" in
    "Backlog")      echo "$KANBAN_COLS_BACKLOG" ;;
    "In Progress")  echo "$KANBAN_COLS_IN_PROGRESS" ;;
    "Review")       echo "$KANBAN_COLS_REVIEW" ;;
    "Done")         echo "$KANBAN_COLS_DONE" ;;
    *)              return 1 ;;
  esac
}

# Generate the full empty KANBAN.md content
kanban_template() {
  echo "# Research Kanban"
  echo ""
  echo "> Managed by \`scripts/lab-kanban.sh\`. Do not edit this file directly."
  echo ""
  for section in "${KANBAN_SECTIONS[@]}"; do
    echo "## ${section}"
    echo ""
    kanban_header_for_section "$section"
    kanban_separator "$(kanban_cols_for_section "$section")"
    echo ""
  done
}
